[project]
name = "social-media"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.31.0",
    "pydantic>=2.0.0",
    "python-dotenv>=1.0.0",
    "pandas",
    "sqlmodel",
    "psycopg2-binary",
    "dbt-postgres",
]

[dependency-groups]
dev = []

[tool.uv]
sources = {}

[tool.uv.workspace]
members = []

[tool.setuptools]
package-dir = {"" = "src"}
